# Generated by Django 4.2.16 on 2025-06-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('carga_horaria', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('professor', models.CharField(max_length=100)),
                ('financiador', models.CharField(blank=True, max_length=100)),
                ('vagas_remuneradas', models.PositiveIntegerField()),
                ('vagas_voluntarias', models.PositiveIntegerField()),
                ('tipo_projeto', models.CharField(choices=[('monitoria', 'Monitoria'), ('tutoria', 'Tutoria'), ('extensao', 'Projeto de Extensão'), ('iniciacao', 'Iniciação Científica')], max_length=20)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
